onEvent('recipes', event => {
    event.remove({output: 'waystones:waystone'})
    event.remove({output: 'waystones:mossy_waystone'})
    event.remove({output: 'waystones:sandy_waystone'})
    event.remove({output: 'waystones:warp_stone'})
    event.remove({output: 'waystones:warp_plate'})
    event.remove({output: 'waystones:bound_scroll'})
    event.remove({output: 'waystones:sharestone'})
    event.remove({output: 'waystones:sharestone'})
})