onEvent("recipes", (event) => {
    let infusionRecipes = [
        {
            input: "minecraft:iron_sword",
            output: "aquamirae:terrible_sword",
            time: 240,
            catalysts: [
                { item: "aquamirae:ship_graveyard_echo", index: 0 },
                { item: "aquaculture:neptunium_ingot", index: 2 },
                { item: "aquaculture:neptunium_ingot", index: 4 },
                { item: "aquaculture:neptunium_ingot", index: 6 },
                { item: "aquamirae:anglers_fang", index: 1 },
                { item: "aquamirae:anglers_fang", index: 3 },
                { item: "aquamirae:anglers_fang", index: 5 },
                { item: "aquamirae:anglers_fang", index: 7 },
            ],
        },
        {
            input: "eidolon:basic_amulet",
            output: "forbidden_arcanus:spectral_eye_amulet",
            time: 100,
            catalysts: [
                { item: "alexsmobs:void_worm_eye", index: 0 },
                { item: "iceandfire:ectoplasm", index: 2 },
                { item: "iceandfire:ectoplasm", index: 4 },
                { item: "iceandfire:ectoplasm", index: 6 },
                { item: "eidolon:pewter_blend", index: 1 },
                { item: "minecraft:ender_eye", index: 3 },
                { item: "eidolon:pewter_blend", index: 5 },
                { item: "minecraft:ender_eye", index: 7 },
            ],
        },
        {
            input: "forbidden_arcanus:stellarite_piece",
            output: "forbidden_arcanus:eternal_stella",
            time: 100,
            catalysts: [
                { item: "enigmaticlegacy:mending_mixture", index: 0 },
                { item: "forbidden_arcanus:xpetrified_orb", index: 2 },
                { item: "forbidden_arcanus:xpetrified_orb", index: 4 },
                { item: "forbidden_arcanus:xpetrified_orb", index: 6 },
                { item: "botania:elementium_ingot", index: 1 },
                { item: "botania:elementium_ingot", index: 3 },
                { item: "botania:elementium_ingot", index: 5 },
                { item: "botania:elementium_ingot", index: 7 },
            ],
        },
        {
            input: "forbidden_arcanus:draco_arcanus_helmet",
            output: "forbidden_arcanus:tyr_helmet",
            time: 100,
            catalysts: [
                { item: "forbidden_arcanus:golden_dragon_scale", index: 0 },
                { item: "forbidden_arcanus:silver_dragon_scale", index: 2 },
                { item: "forbidden_arcanus:silver_dragon_scale", index: 4 },
                { item: "forbidden_arcanus:silver_dragon_scale", index: 6 },
                { tag: "forge:scales/dragon", index: 1 },
                { tag: "forge:scales/dragon", index: 3 },
                { tag: "forge:scales/dragon", index: 5 },
                { tag: "forge:scales/dragon", index: 7 },
            ],
        },
        {
            input: "forbidden_arcanus:draco_arcanus_chestplate",
            output: "forbidden_arcanus:tyr_chestplate",
            time: 100,
            catalysts: [
                { item: "forbidden_arcanus:golden_dragon_scale", index: 0 },
                { item: "forbidden_arcanus:aquatic_dragon_scale", index: 2 },
                { item: "forbidden_arcanus:aquatic_dragon_scale", index: 4 },
                { item: "forbidden_arcanus:aquatic_dragon_scale", index: 6 },
                { tag: "forge:scales/dragon", index: 1 },
                { tag: "forge:scales/dragon", index: 3 },
                { tag: "forge:scales/dragon", index: 5 },
                { tag: "forge:scales/dragon", index: 7 },
            ],
        },
        {
            input: "forbidden_arcanus:draco_arcanus_leggings",
            output: "forbidden_arcanus:tyr_leggings",
            time: 100,
            catalysts: [
                { item: "forbidden_arcanus:golden_dragon_scale", index: 0 },
                { item: "forbidden_arcanus:silver_dragon_scale", index: 2 },
                { item: "forbidden_arcanus:silver_dragon_scale", index: 4 },
                { item: "forbidden_arcanus:silver_dragon_scale", index: 6 },
                { tag: "forge:scales/dragon", index: 1 },
                { tag: "forge:scales/dragon", index: 3 },
                { tag: "forge:scales/dragon", index: 5 },
                { tag: "forge:scales/dragon", index: 7 },
            ],
        },
        {
            input: "forbidden_arcanus:draco_arcanus_boots",
            output: "forbidden_arcanus:tyr_boots",
            time: 100,
            catalysts: [
                { item: "forbidden_arcanus:golden_dragon_scale", index: 0 },
                { item: "forbidden_arcanus:aquatic_dragon_scale", index: 2 },
                { item: "forbidden_arcanus:aquatic_dragon_scale", index: 4 },
                { item: "forbidden_arcanus:aquatic_dragon_scale", index: 6 },
                { tag: "forge:scales/dragon", index: 1 },
                { tag: "forge:scales/dragon", index: 3 },
                { tag: "forge:scales/dragon", index: 5 },
                { tag: "forge:scales/dragon", index: 7 },
            ],
        },
    ];
    infusionRecipes.forEach((recipe) => {
        event.custom({
            type: "betterendforge:infusion",
            input: { item: recipe.input },
            output: recipe.output,
            time: recipe.time,
            catalysts: recipe.catalysts,
        });
    });
});
