
#Settings affecting the logical server side, also valid for single player games.
[server]

	#Settings to tweak the performance, or use cases normally no change should be required here.
	[server.tweaks]
		#Durability (maximum item damage) of the REDIA tool.
		#Range: 750 ~ 4000
		redia_tool_durability = 3000
		#Durability of the REDIA tool in percent, which the tool has when it is crafted. Allows to tune initial repairing investments for getting efficiency and furtune.
		#Range: 50 ~ 100
		redia_tool_initial_durability_percent = 100
		#Defines the efficiency scaling depending on the durability. Ten values have to given as integer numbers, (between 0 and 4), and the curve must be rising left-to-right. 0 corresponds to vanilla diamond tools. The first number specifies the efficiency between 0% and 10% durability, second 10% to 20%, last 90% to 100%.
		redia_tool_efficiency_curve = "0,1,1,2,2,3,3,3,3,4"
		#Defines the fortune depending on the durability. Ten values have to given as integer numbers, (between 0 and 3), and the curve must be rising left-to-right. The first number specifies the furtune between 0% and 10% durability, second 10% to 20%, last 90% to 100%.
		redia_tool_furtune_curve = "0,0,0,0,1,1,1,1,2,3"
		#Disable the REDIA tool feature to prevent accidentally hitting own pets, villagers, or bloody zombie pigmen.
		without_safe_attacking = false

