
[default_gamerule]
doVanillaAttack = true
keepSkills = false
hasFallAnimation = true
disapleEntityUI = false
#Range: 0 ~ 100
weightPenalty = 100

[loot]
skill_book_mob_loot = false
skill_book_chest_loot = false
