
[ShieldList]
	#
	#List of items to considered as shields, any item with right-click functionality will theoretically work
	#Automatically populated with items that have parrying stats set by active datapacks
	shieldList = ["blue_skies:spike_shield", "shieldexp:wooden_shield", "shieldexp:griefer_shield", "blue_skies:moonstone_shield", "shieldexp:iron_shield", "twilightforest:knightmetal_shield", "shieldexp:netherite_shield", "alexsmobs:shield_of_the_deep", "minecraft:shield", "shieldexp:golden_shield", "shieldexp:diamond_shield", "shieldexp:paragon_shield", "artifacts:umbrella", "spartanshields:shield_basic_wood", "spartanshields:shield_basic_stone", "spartanshields:shield_basic_iron", "spartanshields:shield_basic_gold", "spartanshields:shield_basic_diamond", "spartanshields:shield_basic_netherite", "spartanshields:shield_basic_obsidian", "spartanshields:shield_basic_copper", "spartanshields:shield_basic_silver", "spartanshields:shield_basic_lead", "spartanshields:shield_tower_wood", "spartanshields:shield_tower_stone", "spartanshields:shield_tower_iron", "spartanshields:shield_tower_gold", "spartanshields:shield_tower_diamond", "spartanshields:shield_tower_netherite", "spartanshields:shield_tower_obsidian", "spartanshields:shield_tower_copper", "spartanshields:shield_tower_silver", "spartanshields:shield_tower_lead", "forestcraft:prehistoric_shield", "forestcraft:archaic_shield", "bygonenether:gilded_netherite_shield", "dungeons_mobs:royal_guard_shield", "dungeons_mobs:vanguard_shield", "cataclysm:bulwark_of_the_flame", "spartanshields:shield_tower_tin", "spartanshields:shield_tower_nickel", "spartanshields:shield_basic_bronze", "spartanshields:shield_tower_bronze", "spartanshields:shield_tower_constantan", "forbidden_arcanus:obsidian_skull_shield", "spartanshields:shield_basic_nickel", "spartanshields:shield_basic_tin", "spartanshields:shield_tower_invar", "spartanshields:shield_basic_constantan", "undergarden:cloggrum_shield", "spartanshields:shield_basic_invar", "mekanismtools:osmium_shield", "spartanshields:shield_mekanism_refined_glowstone", "mekanismtools:bronze_shield", "spartanshields:shield_botania_manasteel", "ars_nouveau:enchanters_shield", "mod_lavacow:vespa_shield", "spartanshields:shield_tower_steel", "mekanismtools:refined_glowstone_shield", "spartanshields:shield_mekanism_refined_obsidian", "atum:brigand_shield", "spartanshields:shield_basic_electrum", "spartanshields:shield_mekanism_osmium", "spartanshields:shield_mekanism_powered_basic", "outvoted:wildfire_shield", "atum:stoneguard_shield", "spartanshields:shield_botania_terrasteel", "spartanshields:shield_mekanism_lapis_lazuli", "mekanismtools:refined_obsidian_shield", "spartanshields:shield_tower_electrum", "immersiveengineering:shield", "spartanshields:shield_botania_elementium", "spartanshields:shield_basic_steel", "spartanshields:shield_mekanism_powered_elite", "spartanshields:shield_mekanism_powered_ultimate", "mekanismtools:lapis_lazuli_shield", "mekanismtools:steel_shield", "spartanshields:shield_mekanism_powered_advanced"]
	#
	#List of items to not consider as shields, even if they have stats set by a datapack
	shieldBlacklist = []

[Modifiers]
	#
	#Disable the cooldown when the player lowers their shield
	noLoweringCooldown = true
	#
	#Disable putting shields on cooldown at all
	noCooldown = false
	#
	#Make all shields have vanilla movement speed
	noSpeedModifier = false
	#
	#Make shields only block partial damage from explosions when not parrying
	harderExplosions = true
	#
	#Double the parry window for a more relaxed experience
	lenientParryMode = false
	#
	#Double the shield stamina for a more relaxed experience
	lenientStaminaMode = false

