
#General settings for the mod.
[general]
	#Should enchantability be shown?
	show-enchantability = false
	#Should enchantability always be shown?
	always-show-enchantability = false
	#Should harvest level be shown?
	show-harvest-level = false
	#Should mining efficiency be shown?
	show-efficiency = false
	#Should repair cost be shown in the anvil GUI?
	show-repair-cost = false
	#Should the durability be shown on the tool?
	show-durability = false

